domain_path: C:\Users\IECS-Lab\Desktop\vitis_2024_workspace\dma_loopback\export\dma_loopback\sw\standalone_psu_cortexa53_0
app_src_dir: E:\Vitis\2024.1\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
